### ISSUE TITLE
Abstract Padding

### ISSUE THREAD

**Issue by pjchong91** [AndreiEgorov/instanews-app#3]
There is currently no padding around the abstract <p> and this is causing the text to run into the edge of the container.  Would recommend adding margin: 10px to <p> element.

**Comment by rcass** [comment]
Hey @pjchong91 not quite sure if the markup above just didn't turn out the way you expected above.

Looks like you are trying to quote a line of code or something. If you want to ref some code or quote code you can use back ticks (`.className`) or use that copy permalink to quote entire block of code.

**Comment by AndreiEgorov** [comment]
Hey @pjchong91 , thank you for your suggestion. Abstract looks much nicer now.
